-- TG-Jinni PostgreSQL schema for Cloudflare Hyperdrive + Python Workers.
-- Safe to run more than once for a fresh database. For an existing DB, review before applying.

CREATE TABLE IF NOT EXISTS users (
  telegram_id BIGINT PRIMARY KEY,
  username VARCHAR(64),
  first_name VARCHAR(128),
  coins_available BIGINT NOT NULL DEFAULT 0,
  coins_hold BIGINT NOT NULL DEFAULT 0,
  games_played INTEGER NOT NULL DEFAULT 0,
  games_won INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS entities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  username VARCHAR(64) UNIQUE,
  telegram_chat_id BIGINT UNIQUE,
  entity_type VARCHAR(32) NOT NULL DEFAULT 'channel',
  avatar_url TEXT,
  description TEXT,
  owner_telegram_id BIGINT REFERENCES users(telegram_id),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_promoted BOOLEAN NOT NULL DEFAULT FALSE,
  reports_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS channel_ownerships (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  telegram_id BIGINT NOT NULL REFERENCES users(telegram_id) ON DELETE CASCADE,
  verification_method VARCHAR(32) NOT NULL,
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(entity_id, telegram_id)
);

CREATE TABLE IF NOT EXISTS questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  category VARCHAR(64) NOT NULL DEFAULT 'general',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS entity_question_weights (
  entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  weight DOUBLE PRECISION NOT NULL CHECK(weight >= 0 AND weight <= 1),
  PRIMARY KEY(entity_id, question_id)
);

CREATE TABLE IF NOT EXISTS game_sessions (
  id UUID PRIMARY KEY,
  telegram_id BIGINT NOT NULL REFERENCES users(telegram_id),
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  question_count INTEGER NOT NULL DEFAULT 0,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMPTZ,
  guessed_entity_id INTEGER REFERENCES entities(id),
  engine_state JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS game_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID NOT NULL REFERENCES game_sessions(id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL REFERENCES questions(id),
  answer_value DOUBLE PRECISION NOT NULL CHECK(answer_value >= 0 AND answer_value <= 1),
  question_number INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pending_entities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_telegram_id BIGINT NOT NULL REFERENCES users(telegram_id),
  title VARCHAR(128) NOT NULL,
  username VARCHAR(64),
  telegram_chat_id BIGINT,
  proposed_question TEXT,
  ownership_verified BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  moderator_telegram_id BIGINT,
  moderator_comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS entity_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  telegram_id BIGINT NOT NULL REFERENCES users(telegram_id) ON DELETE CASCADE,
  reason VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(entity_id, telegram_id)
);

CREATE TABLE IF NOT EXISTS coin_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(telegram_id),
  amount BIGINT NOT NULL,
  type VARCHAR(64) NOT NULL,
  reference_id VARCHAR(128),
  status VARCHAR(32) NOT NULL DEFAULT 'completed',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  description TEXT,
  task_type VARCHAR(32) NOT NULL,
  entity_id INTEGER REFERENCES entities(id),
  channel_username VARCHAR(64),
  channel_id BIGINT,
  reward_coins INTEGER NOT NULL DEFAULT 50,
  hold_hours INTEGER NOT NULL DEFAULT 48,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_tasks (
  user_id BIGINT NOT NULL REFERENCES users(telegram_id),
  task_id INTEGER NOT NULL REFERENCES tasks(id),
  status VARCHAR(32) NOT NULL DEFAULT 'started',
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  rewarded_at TIMESTAMPTZ,
  hold_until TIMESTAMPTZ,
  PRIMARY KEY(user_id, task_id)
);

CREATE TABLE IF NOT EXISTS shop_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  description TEXT,
  item_type VARCHAR(32) NOT NULL,
  price_coins BIGINT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS user_inventory (
  user_id BIGINT NOT NULL REFERENCES users(telegram_id),
  item_id INTEGER NOT NULL REFERENCES shop_items(id),
  quantity INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(user_id, item_id)
);

CREATE TABLE IF NOT EXISTS shop_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(telegram_id),
  item_id INTEGER NOT NULL REFERENCES shop_items(id),
  price_coins BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS promotion_campaigns (
  id UUID PRIMARY KEY,
  entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  owner_telegram_id BIGINT NOT NULL REFERENCES users(telegram_id),
  impressions_total INTEGER NOT NULL DEFAULT 4500,
  impressions_used INTEGER NOT NULL DEFAULT 0,
  clicks_total INTEGER NOT NULL DEFAULT 0,
  price_rub INTEGER NOT NULL DEFAULT 180,
  status VARCHAR(32) NOT NULL DEFAULT 'pending_payment',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS promotion_impressions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id UUID NOT NULL REFERENCES promotion_campaigns(id) ON DELETE CASCADE,
  telegram_id BIGINT NOT NULL REFERENCES users(telegram_id),
  game_session_id UUID REFERENCES game_sessions(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(campaign_id, telegram_id)
);

CREATE TABLE IF NOT EXISTS promotion_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id UUID NOT NULL REFERENCES promotion_campaigns(id) ON DELETE CASCADE,
  telegram_id BIGINT REFERENCES users(telegram_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payments (
  id UUID PRIMARY KEY,
  telegram_id BIGINT NOT NULL REFERENCES users(telegram_id),
  campaign_id UUID REFERENCES promotion_campaigns(id),
  amount INTEGER NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'RUB',
  status VARCHAR(32) NOT NULL,
  provider_payment_id VARCHAR(255) UNIQUE,
  invoice_payload VARCHAR(128) UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  paid_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_entities_owner ON entities(owner_telegram_id);
CREATE INDEX IF NOT EXISTS idx_entities_active ON entities(is_active, entity_type, id);
CREATE INDEX IF NOT EXISTS idx_reports_entity ON entity_reports(entity_id, created_at);
CREATE INDEX IF NOT EXISTS idx_tasks_active ON tasks(is_active, id);
CREATE INDEX IF NOT EXISTS idx_user_tasks_hold ON user_tasks(status, hold_until);
CREATE INDEX IF NOT EXISTS idx_campaign_status ON promotion_campaigns(status, created_at);
CREATE INDEX IF NOT EXISTS idx_ownership_recheck ON channel_ownerships(verified, verified_at);
CREATE INDEX IF NOT EXISTS idx_pending_status ON pending_entities(status, created_at);
CREATE INDEX IF NOT EXISTS idx_payments_payload ON payments(invoice_payload);

INSERT INTO questions (text, category)
SELECT v.text, v.category
FROM (VALUES
  ('Канал в основном развлекательный?', 'content'),
  ('Канал связан с новостями?', 'content'),
  ('На канале часто публикуют мемы?', 'content'),
  ('На канале есть полезные инструкции или гайды?', 'content'),
  ('Канал про технологии?', 'topic'),
  ('Канал про игры?', 'topic'),
  ('Канал про бизнес или заработок?', 'topic'),
  ('Канал про образование?', 'topic'),
  ('Канал про финансы?', 'topic'),
  ('Канал про криптовалюты?', 'topic'),
  ('Канал ориентирован на широкую аудиторию?', 'audience'),
  ('Публикации выходят каждый день?', 'activity'),
  ('В канале больше текста, чем картинок?', 'format'),
  ('В канале много коротких постов?', 'format'),
  ('Канал часто публикует ссылки?', 'format'),
  ('Есть выраженный автор или ведущий?', 'brand'),
  ('Канал связан с конкретным городом или регионом?', 'geo'),
  ('Канал ориентирован в основном на русскоязычную аудиторию?', 'geo'),
  ('Публикации часто содержат призывы подписаться на другие ресурсы?', 'promotion'),
  ('Контент рассчитан на ежедневное возвращение аудитории?', 'audience')
) AS v(text, category)
WHERE NOT EXISTS (SELECT 1 FROM questions q WHERE q.text = v.text);

INSERT INTO shop_items (title, description, item_type, price_coins, metadata)
SELECT 'Буст профиля', 'Демонстрационный предмет магазина MVP.', 'profile_boost', 200, '{}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM shop_items WHERE title='Буст профиля');
