-- Upgrade legacy TG-Jinni PostgreSQL schema for the Cloudflare Worker.
-- Run after a backup. All statements are intended to be repeatable.

CREATE TABLE IF NOT EXISTS entity_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  telegram_id BIGINT NOT NULL REFERENCES users(telegram_id) ON DELETE CASCADE,
  reason VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(entity_id, telegram_id)
);

-- Apply this only when migrating an existing TG-Jinni PostgreSQL database.
-- Back up the database first.

ALTER TABLE payments ADD COLUMN IF NOT EXISTS invoice_payload VARCHAR(128);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payments_invoice_payload ON payments(invoice_payload) WHERE invoice_payload IS NOT NULL;

-- Make old duplicate impression rows harmless before adding the uniqueness rule.
DELETE FROM promotion_impressions a
USING promotion_impressions b
WHERE a.id > b.id
  AND a.campaign_id = b.campaign_id
  AND a.telegram_id IS NOT DISTINCT FROM b.telegram_id;

CREATE UNIQUE INDEX IF NOT EXISTS uq_promotion_impressions_campaign_user
  ON promotion_impressions(campaign_id, telegram_id);

CREATE INDEX IF NOT EXISTS idx_payments_campaign ON payments(campaign_id, created_at);
